apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

        # TODO:
        # 1. Rewrite file to match with deployment manifest in the cloud
        # 2. Create Secret for ENV variables
        # 3. Pass secret values into deployment ENV variables